import { Inter } from 'next/font/google'

import ogImage from '../public/favicon.ico'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Anas ESSAMLALI/Portfolio',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta property="og:image" content={ogImage} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
